Del 744 package creation
janis-commerce/request pull request #1
Opened 2021-01-18 23:03 UTC by diegobr89

### LINK AL TICKET

https://fizzmod.atlassian.net/browse/DEL-734

### LINK A SUBTAREA

https://fizzmod.atlassian.net/browse/DEL-744

### DESCRIPCION DEL REQUERIMIENTO

Contar con un package de npm para comunicarse con sistemas externos a Janis, para esto se puede utilizar\
como base el módulo request que se encuentra en las diferentes integraciones.

Este package debe contar con los métodos comunes de request para los protocolos http y https

* GET
* POST
* PUT
* PATCH
* DELETE

Se debe poder invocar de forma asíncrona cada uno de estos métodos\
Adicional a esto debe poder agregar de forma sencilla:

* Headers
* Path Parameters
* Query Parameters

Se deberán agregar otros parámetros que se consideren importantes, relevantes o necesarios\
Así como tener getters para las siguientes propiedades:

* El status code
* Los headers de la respuesta
* La respuesta como Buffer
* Respuesta en formato JSON

Se deberán agregar las propiedades que se consideren importantes, relevantes o necesarias

#### Qué se espera?
De este desarrollo se espera contar con un package npm el cual permita realizar comunicaciones con sistemas externos.\
Se espera entonces, Realizar una comunicación con una API Rest para cada uno de los métodos 

* GET
* POST
* PUT
* PATCH
* DELETE

Poder agregar en estas comunicaciones:

* headers
* path parameters
* query parameters

Una vez realizada la comunicación se debe poder obtener de forma sencilla

* El status code
* Los headers de la respuesta
* La respuesta como Buffer
* Respuesta en formato JSON
* Contar con un documentación que permita utilizar de forma simple y sencilla este package

 
### DESCRIPCION DE LA SOLUCION
* Se creo el package "request"
* Se creo la clase "Request", con las funcionalidades descriptas en el requerimiento.\
Dicha clase retorna siempre una instancia de "RequestResponse" que contiene toda la informacion de la respuesta,\
a excepcion que exista un error.
* Se creo la clase RequestError para el manejo de errores
* Se crearon los test
* Se creo el README.md con toda la documentacion del funcionamiento de este package

2021-01-19 13:08 UTC, gastonpereyra commented on package.json
> +    "test-ci": "nyc --reporter=html --reporter=text mocha --exit --recursive tests/",
:warning: Si te fijas el workflow del Action de Coverage esta fallando:

https://github.com/janis-commerce/request/pull/1/checks?check_run_id=1724429088

Eso es porque este script esta mal.

Asi debería ser

```suggestion
    "test-ci": "nyc --reporter=lcov --reporter=text-summary mocha --exit --recursive tests/",
```

2021-01-19 13:14 UTC, gastonpereyra commented
Con los Actions, travis deja de ser necesario, por eso:

* el archivo `.travis.yml` hay que eliminarlo

2021-01-19 13:16 UTC, gastonpereyra commented on README.md
>  [![Build Status](https://travis-ci.org/janis-commerce/request.svg?branch=master)](https://travis-ci.org/janis-commerce/request)
```suggestion
![Build Status](https://github.com/janis-commerce/request/workflows/Build%20Status/badge.svg?branch=master)
```

2021-01-21 16:04 UTC, deveplon commented
Dieguito se te está rompiendo uno de los checks _Coverage Status / Build (push) Failing after 24s — Build_

2021-01-21 16:43 UTC, deveplon commented on lib/request-error.js
>  class RequestError extends Error {
Dieguito esto es solo por estandarizar un poco, aquí podrías hacer un
`module.exports = class RequestError extends Error {`

2021-01-21 17:07 UTC, deveplon commented on lib/request-utils.js
> +		return Object.entries(pathParams).reduce((path, [key, value]) => {
Dieguito esto se podría resolver así, a mi parecer es mas óptimo y simple debido a que el replace ya lo hace por vos. 
`return pathTemplate.replace(/{(.*?)}/g, param => pathParams[param.slice(1, -1)])`

2021-01-21 17:21 UTC, deveplon commented on lib/request.js
> +			const callback = res => {
Dieguito ya que utilizaste esta aproximación que me parece muy buena prodrias convertir esta constante en una función como por ejemplo `processCall`  o bueno algo por el estilo y podrías invocar esa función abajo. Qué te parece?

2021-01-21 17:23 UTC, deveplon commented on lib/request.js
> +			const requestProtocol = protocol.replace(':', '');
Dieguito que te parece hacer esto en el RequestUtils y que lo tengas de una vez aquí así procesamos todo en la misma parte

2021-01-21 17:29 UTC, deveplon commented on tests/request.js
> +		const reqResponse = 	await Request[fn](url, payload);
Dieguito fijate que tenes un espacio raro aquí

2021-01-21 17:33 UTC, deveplon commented on lib/request.js
> +					const responseBody = JSON.parse(rawResponse);
Dieguito en esta parte fijate que si la respuesta es un string, un base64 o un buffer de un archivo o algo por el estilo, va a romper en esta linea. Esto se podría hacer pero por ejemplo dentro de un `try/catch`  para que no se rompa en caso de que no sea un JSON

2021-01-21 17:42 UTC, deveplon requested changes

2021-01-21 17:42 UTC, deveplon commented on lib/request.js
> +			const callback = res => {
Dieguito ya que utilizaste esta aproximación que me parece muy buena prodrias convertir esta constante en una función como por ejemplo processCall o bueno algo por el estilo y podrías invocar esa función abajo. Qué te parece?

2021-01-21 17:42 UTC, deveplon commented on lib/request.js
> +					const responseBody = JSON.parse(rawResponse);
Dieguito en esta parte fijate que si la respuesta es un string, un base64 o un buffer de un archivo o algo por el estilo, va a romper en esta linea. Esto se podría hacer pero por ejemplo dentro de un try/catch para que no se rompa en caso de que no sea un JSON

2021-01-21 17:42 UTC, deveplon commented on lib/request.js
> +			const requestProtocol = protocol.replace(':', '');
Dieguito que te parece hacer esto en el RequestUtils y que lo tengas de una vez aquí así procesamos todo en la misma parte

2021-01-21 17:42 UTC, deveplon commented on tests/request.js
> +		const reqResponse = 	await Request[fn](url, payload);
Dieguito fijate que tenes un espacio raro aquí. Hay por ahi algunos asi

2021-01-21 17:42 UTC, deveplon commented on lib/request-utils.js
> +		return Object.entries(pathParams).reduce((path, [key, value]) => {
Dieguito esto se podría resolver así, a mi parecer es mas óptimo y simple debido a que el replace ya lo hace por vos.
`return pathTemplate.replace(/{(.*?)}/g, param => pathParams[param.slice(1, -1)])`

2021-01-21 17:42 UTC, deveplon commented on lib/request-error.js
>  class RequestError extends Error {
Dieguito esto es solo por estandarizar un poco, aquí podrías hacer un
`module.exports = class RequestError extends Error {`

2021-01-21 17:58 UTC, jormaechea commented on lib/request.js
> +			const headers = { ...params.headers, ...this.defaultHeaders };
Ojo acá, que no hay forma de pisar los `defaultHeaders`.. Deberíamos invertir el orden para que los custom pisen a los default.

2021-01-21 19:14 UTC, deveplon commented
Una pregunta general, que pasa si se obtiene un 400 o un 500 en la respuesta, tendríamos forma después de obtener ese código y la respuesta? Esto lo digo porque en algunos casos se puede necesitar este dato

2021-01-21 20:58 UTC, jormaechea commented on lib/request-utils.js
> +		return Object.entries(pathParams).reduce((path, [key, value]) => {
En este caso:

```js
const pathTemplate = '/foo/{first}/bar/{second}';
const pathParams = { first: 'joaco' }
```

Las dos soluciones funcionarian distinto:
- La primera, resulta en `'/foo/joaco/bar/{second}';`
- La segunda, resulta en `'/foo/joaco/bar/undefined';`
Ni idea que es mejor o peor. Se los dejo a ustedes.

Lo que si, en la solución actual tengan cuidado que se puede hacer un injection en la RegExp..
Por ejemplo:

```js
const pathTemplate = '/foo/{first}/bar/{second}';
const pathParams = { ['.+}.*']: 'joaco' };
```
Al reemplazar, quedaria `/foo/joaco`.
Dependiendo de donde salgan los `pathParams`, puede ser peligroso.

2021-01-22 21:27 UTC, diegobr89 commented on lib/request.js
> +					const responseBody = JSON.parse(rawResponse);
El json parse no explota prque rawresponse es un buffer. Sea lo que sea que contiene el buffer, lo va a devolver parseado

2021-01-22 21:30 UTC, diegobr89 commented on lib/request-utils.js
> +		return Object.entries(pathParams).reduce((path, [key, value]) => {
Joaco, no le veo problemas de seguridad por inyeccion a algo que es una lib para hacer request a urls externas. Si lo hicieras, te estarias poniendo el palo en tu propia rueda, digo.. podes directamente mandar fruta en la url y es lo mismo. 
Igual lo cambio

2021-01-22 21:37 UTC, diegobr89 commented
@deveplon  en respuesta a tu pregunta de que pasa con los error codes.. La respuesta SIEMPRE es una instancia de RequestResponse por ende tiene todos estos datos:

complete,
aborted,
httpVersion,
rawHeaders,
headers,
statusCode,
statusMessage,
body
rawBody,
originRequest

El status de la respuesta está en statusCode

2021-01-25 13:09 UTC, deveplon approved these changes

2021-01-25 15:04 UTC, gastonpereyra approved these changes

2021-01-25 16:59 UTC, jormaechea requested changes

2021-01-25 16:59 UTC, jormaechea commented on README.md
Sería bueno meter al menos un ejemplo, para poder usarlo rápidamente sin leer toda la docu.

2021-01-25 16:59 UTC, jormaechea commented on lib/request-response.js
> +			return responseBody;
O más simplemente:
```suggestion
			return JSON.parse(rawBody);
```

2021-01-25 16:59 UTC, jormaechea commented on lib/request-utils.js
> +	 * @returns {any}
```suggestion
	 * @param {*} [data='']
	 * @returns {string|Buffer}
```

2021-01-25 16:59 UTC, jormaechea commented on lib/request-utils.js
> +		const urlPath = path.replace(slashRegex, '') || formattedPathName;
```suggestion
		const urlPath = path.replace(slashRegex, '') || decodeURIComponent(pathname.replace(slashRegex, '',));
```
o
```suggestion
		const urlPath = (path || decodeURIComponent(pathname)).replace(slashRegex, '',));
```

Sino, quizás estamos armando `formattedPathName` y no se usa..

2021-01-25 16:59 UTC, jormaechea commented on lib/request-utils.js
> +	 * @param {object} [pathParams={}] CallOptions pathParams
```suggestion
	 * @param {object} [pathParams={}] A key-value mapping to replace the path variables
```

2021-01-25 16:59 UTC, jormaechea commented on lib/request-utils.js
> +		return pathTemplate.replace(/{(.*?)}/g, param => pathParams[param.slice(1, -1)]);
Esto es lo que habíamos charlado, de restringir un poco, y de paso cambiar el `*` por `+`, para que no matchee contra `{}`:

```suggestion
		return pathTemplate.replace(/{([a-z0-9_-]+?)}/ig, param => pathParams[param.slice(1, -1)]);
```

2021-01-25 16:59 UTC, jormaechea commented on lib/request-utils.js
> +	}
Son un par de lineas más, pero queda a prueba de balas.. Funciona hasta con el header `ContEnT-tyPE` 😛 
```suggestion
	function validateResponseHeaders(headers, strictMode) {
		if(!strictMode)
			return;

		const contentTypeHeader = Object.keys(headers)
			.find(headerName => headerName.toLowerCase() === 'content-type');

		const contentType = contentTypeHeader ? headers[contentTypeHeader] : '';

		if(contentType.toLowerCase() !== 'application/json') {
			throw new RequestError('Response is not a valid "application/json"',
				RequestError.REQUEST_ERROR);
		}
	}
```

2021-01-25 16:59 UTC, jormaechea commented on lib/request.js
> +	 */
```suggestion
/**
 * @typedef PathTemplate
 * @type {string} A string path. Supports templating in "{variable}" format. IE: "/api/users/{userId}/contacts"
 */

/**
 * @typedef CallOptions
 * @type {object}
 * @property {object} headers - Custom headers on request. Define as { [headerName]: headerValue }
 * @property {object} pathParams - Replace variables in path declared as "{variable}". Define structure as { [variableNameInPath]: valueForReplace }
 * @property {object} queryParams - Query parameters / filters on request. Define structure as { [queryVariableName]: value }
 * @property {PathTemplate} path - The request path
 * @property {boolean} strictMode - When this flag is set as true, the request response content-type should be application/json or error will thrown
 * @property {string} endpoint - The request endpoint. Protocol and path are optionals. When no protocol specified, http goes by default. Supports *PathTemplate
 * @property {string} method - The request method. 'GET' is set by default
 * @property {any} body - The request body (if request method accepts it). Can be a valid object, Array, string, or any serializable type.
 */

/**
 * @typedef RequestOptions
 * @type {object}
 * @property {object} headers - Custom headers on request. Define as { [headerName]: headerValue }
 * @property {object} pathParams - Replace variables in path declared as "{variable}". Define structure as { [variableNameInPath]: valueForReplace }
 * @property {object} queryParams - Query parameters / filters on request. Define structure as { [queryVariableName]: value }
 * @property {PathTemplate} path - The request path
 * @property {boolean} strictMode - When this flag is set as true, the request response content-type should be application/json or error will thrown
 */

/**
 * @typedef RequestResponse
 * @type {object}
 * @property {boolean} complete Flag that represents that if operation was completed
 * @property {boolean} aborted Flag that represents that if operation was aborted
 * @property {string} httpVersion String with http protocol version of the response sent
 * @property {Array<String>} rawHeaders Request headers as array of srings
 * @property {object} headers Response headers. Formatted as { [headerName]: headerValue }
 * @property {number} statusCode Response status code
 * @property {string} statusMessage Response status message
 * @property {any} body Response body. Can be a valid object, Array, string, or any serializable type.
 * @property {Array} rawBody Response body without serialization.
 * @property {CallOptions} originRequest Used to make another request based on the origin request. Ie: For retry the same request
 */
```

2021-01-25 16:59 UTC, jormaechea commented on tests/request.js
> +const sandbox = require('sinon').createSandbox();
Hace muchas versiones que `sinon` ya es un sandbox y no hay que crear otro:
```suggestion
const sinon = require('sinon');
```

2021-01-25 16:59 UTC, jormaechea commented on tests/request.js
> +	it('Should make a get in strict mode and throw an error', async () => {
```suggestion
	it('Should throw an error if response is not application/json when strict mode is enabled', async () => {
```

2021-01-26 13:16 UTC, jormaechea approved these changes

2021-01-26 13:16 UTC, merged