Del 931 - Mejorar y estandarizar package de Request en DHL
janis-commerce/request pull request #2
Opened 2021-07-15 13:56 UTC by fedeatanasoff

**LINK**
historia https://fizzmod.atlassian.net/browse/DEL-889
subtarea: https://fizzmod.atlassian.net/browse/DEL-931

NOTA
como el modulo ya trabajaba por default de manera 'segura', se modifico para que ahora arroje un error en respuestas con status code >= 400 para asi poder agregar la clase `RequestSafe`

2021-07-16 21:07 UTC, gastonpereyra commented on lib/request.js
> +	static async call({ body, strictMode, safeMode, ...params }) {
Me genera mucho ruido que el `safeMode` este aca, como un parametro del `call`.

Me parece un tanto "incomodo" al usuarlo, si quiero pasarle más paramentros, por ejemplo.

Pero además queda diferente al de la otra clase, y creo que la idea es que las 2 clases para afuera el método 
principial fuera identico, y su comportamiento difernte.

Para mi, el `safeMode` debe ser un `getter` o algo asi.

De esa manera `Request` tiene ese getter en un valor default, `false` , mientras que `Request-safe` lo sobrescribe y settea en `true`. Y asi el método `call` queda igual para los 2 casos.

2021-07-16 21:08 UTC, gastonpereyra commented on lib/request.js
> +			return resolve(formattedResponse);
```suggestion
			this.response  = new RequestResponse(incommingMessage, rawResponse);

			return resolve(this.response );
```

2021-07-16 21:13 UTC, gastonpereyra commented on README.md
> +If you want to handle the error safely you can use `RequestSafe`
```suggestion
Making a custom request.

> :warning:  When the response **status code is greater than or equal to 400 throws an error.**

```

2021-07-16 21:16 UTC, gastonpereyra commented on README.md
> +Making a custom safe request
```suggestion
Making a custom safe request

> :warning:  If you want to handle the error safely. **NOT THROW**
```

2021-07-16 21:17 UTC, gastonpereyra commented on README.md
> +**Read only**: true
:warning:  Guarda que los Read Only te quedaron en la misma linea

2021-07-16 21:20 UTC, gastonpereyra commented on README.md
> +Now `Request`, in addition to being required in another way, throws an error if the response status code if >= 400
Pondría un ejemplo de como se requeria antes y uno como el de ahora.

2021-07-16 21:20 UTC, gastonpereyra requested changes
Deje comentarios sobre algunos cambios

2021-07-20 21:40 UTC, gastonpereyra approved these changes

2021-07-21 20:53 UTC, jormaechea requested changes
@fedeatanasoff te deje un par de comentarios y sumo otro acá..

Me choreaste la parte de obtener la ultima request:
> Se deben disponibilizar métodos para obtener la última request realizada (httpMethod, endpoint, headers y body, si aplica), y para obtener la última response obtenida (statusCode, headers y body)

2021-07-21 20:53 UTC, jormaechea commented on README.md
> +    * [.httpMethod](#Request.defaultHeaders)
Acá quedó bardeado el link..

2021-07-21 20:53 UTC, jormaechea commented on README.md
> +const { Request } = require('@janiscommerce/request');
La migración tiene que ser a la clase que mantiene el comportamiento..

```suggestion
const { RequestSafe } = require('@janiscommerce/request');
```

2021-07-21 20:53 UTC, jormaechea commented on lib/request.js
> +	 * @readonly
Ojo que los `@readonly` suelen traer problemas en la generacion de types de los packages que dependen de este.. Mejor saquemoslos.. Lo mismo con los `@static`.. TS/VSCode son bastante piolas y lo saben solos de todos modos..

2021-07-21 20:53 UTC, jormaechea commented on lib/request.js
> +		const response = await Request.makeRequest(params, body, strictMode);
Y por que no?

```suggestion
		const response = await this..makeRequest(params, body, strictMode);
```

2021-07-22 18:08 UTC, fedeatanasoff commented on README.md
> +    * [.httpMethod](#Request.defaultHeaders)
jaja no, habia entendio que tenia que implementar getters para httpMethod, endopoint, etc individuales.. ahi lo modifico

2021-07-23 16:10 UTC, jormaechea approved these changes
🚀

2021-07-23 16:10 UTC, merged